name: iOS • EAS Build & Submit

on:
  workflow_dispatch:
  push:
    tags:
      - 'ios-v*'     # e.g. git tag ios-v1.0.0+1 && git push --tags

# Prevent overlapping iOS builds on the same ref
concurrency:
  group: ios-eas-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Logs into Expo and makes latest Expo/EAS CLIs available
      - name: Setup Expo/EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      # Builds iOS on Expo’s cloud; --auto-increment bumps iOS buildNumber automatically
      - name: EAS build (iOS • production)
        run: npx eas build --platform ios --profile production --non-interactive --auto-increment --wait

      # Submits the most recent iOS build to TestFlight (App Store Connect)
      - name: Submit to TestFlight
        run: npx eas submit -p ios --latest --non-interactive
